import React from "react";
import { useForm } from "react-hook-form";

import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";

import "./RegistrationForm.css";

type FormData = {
   firstName: string,
   lastName: string,   
   email: string;
   password: string;
   confirmPassword: string;
   acceptTerms: boolean;
};

const RegistrationForm: React.FC = () => {
   const {
      register,
      handleSubmit,
      formState: { errors, isSubmitting },
      setError,
      getValues,
   } = useForm<FormData>({
      mode: "onSubmit",
      reValidateMode: "onChange",
      shouldFocusError: true,
      defaultValues: {
         firstName: "",
         lastName: "",
         email: "",
         password: "",
         confirmPassword: "",
         acceptTerms: false,
      },
   });

   const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/;
   
   const onSubmit = async (formData: FormData) => {
      const email = formData.email.trim().toLowerCase();

      // ======================================================
      // 🔧 BACKEND INTEGRATION — REPLACE THIS SECTION
      // Explanation & example generated by ChatGPT
      //
      // TODO: Uncomment this block when backend is connected.
      // - Use an env var for base URL: import.meta.env.VITE_API_URL
      // - Backend should return 201/200 on success.
      // - Backend should return 409 (EMAIL_TAKEN) when email already exists.
      // - Keep server-side validation even if client does basic checks.
      // ======================================================
      

      // try {
      //   const res = await fetch(`${import.meta.env.VITE_API_URL}/auth/register`, {
      //      method: "POST",
      //      headers: { "Content-Type": "application/json" },
      //      body: JSON.stringify({
      //         firstName: formData.firstName.trim(),
      //         lastName: formData.lastName.trim(),
      //         email, // already trimmed & lowercased above
      //         password: formData.password,
      //         acceptTerms: formData.acceptTerms,
      //      }),
      //   });

      //   if (res.status === 409) {
      //      setError("email", { message: "Email already in use" });
      //      return;
      //   }

      //   if (!res.ok) {
      //      const err = await res.json().catch(() => null);
      //      setError("email", { message: err?.message ?? "Registration failed" });
      //      return;
      //   }

      // TODO: Handle success (e.g., toast + navigate("/signin"))
      // } catch {
      // setError("email", { message: "Network error, try again" });
      // return;
      // }
      // ======================================================
      

      // TEMPORARY: Simulating existing email (remove later)
      const takenEmails = ["taken@example.com"];
      if (takenEmails.includes(email)) {
         setError("email", { message: "Email already in use" });
         return;
      }

      // TEMPORARY: Fake delay to simulate submit (remove later)
      await new Promise((resolve) => setTimeout(resolve, 1000));
   };



   return (
      <div className="registration-container">
         <div className="registration-frame">
            {/* IMAGE SECTION */}
            <div className="image-section">
               <img
                  src="/images/register-image.png"
                  alt="Gym workout"
                  className="image"
               />
               <div className="image-overlay">
                  <h1 className="image-title text-4xl text-right font-bold italic">CoreGymClub</h1>
                  <p className="image-tagline font-bold text-2xl">
                     Transform Your Body. Elevate Your Life.
                  </p>
               </div>
            </div>

            {/* FORM */}
            <form className="form" onSubmit={handleSubmit(onSubmit)} noValidate aria-busy={isSubmitting}>
               <h2 className="form-title text-3xl font-bold">Join Core Gym Club</h2>
               <p className="form-subtitle text-lg">
                  Create your account to unlock your fitness journey.
               </p>

               {/* Screen-reader for submitting */}
               <span className="sr-only" role="status" aria-live="polite">
                  {isSubmitting ? "Submitting your registration..." : ""}
               </span>

               {/* First Name */}
               <div className="form-group">
                  <Label className="form-label text-sm font-bold" htmlFor="firstName">
                     First Name
                  </Label>
                  <Input
                     id="firstName"
                     className="form-input"
                     placeholder="Enter your first name"
                     type="text"
                     autoComplete="given-name"
                     aria-invalid={!!errors.firstName}
                     {...register("firstName", {
                        required: "First name is required",
                        minLength: {
                           value: 2,
                           message: "First name must be at least 2 characters",
                        },
                        validate: (value) =>
                           value.trim().length > 0 ||
                           "First name cannot be empty",
                     })}
                  />
                  {errors.firstName && (
                     <p className="form-error text-sm" aria-live="polite">
                        {errors.firstName.message}
                     </p>
                  )}
               </div>

               {/* Last Name */}
               <div className="form-group">
                  <Label className="form-label text-sm font-bold" htmlFor="lastName">
                     Last Name
                  </Label>
                  <Input
                     id="lastName"
                     className="form-input"
                     placeholder="Enter your last name"
                     type="text"
                     autoComplete="family-name"
                     aria-invalid={!!errors.lastName}
                     {...register("lastName", {
                        required: "Last name is required",
                        minLength: {
                           value: 2,
                           message: "Last name must be at least 2 characters",
                        },
                        validate: (value) =>
                           value.trim().length > 0 ||
                           "Last name cannot be empty",
                     })}
                  />
                  {errors.lastName && (
                     <p className="form-error text-sm" aria-live="polite">
                        {errors.lastName.message}
                     </p>
                  )}
               </div>

               {/* Email */}
               <div className="form-group">
                  <Label className="form-label text-sm font-bold" htmlFor="email">
                     Email Address
                  </Label>
                  <Input
                     id="email"
                     className="form-input"
                     placeholder="your@email.com"
                     type="email"
                     autoComplete="email"
                     aria-invalid={!!errors.email}
                     {...register("email", {
                        required: "Email is required",
                        pattern: {
                           value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                           message: "Invalid email format",
                        },
                        validate: (value) =>
                           value.trim().length > 0 || "Email cannot be empty",
                     })}
                  />
                  {errors.email && (
                     <p className="form-error text-sm" aria-live="polite">
                        {errors.email.message}
                     </p>
                  )}
               </div>

               {/* Password */}
               <div className="form-group">
                  <Label className="form-label text-sm font-bold" htmlFor="password">
                     Password
                  </Label>
                  <Input
                     id="password"
                     className="form-input"
                     placeholder="*********"
                     type="password"
                     autoComplete="new-password"
                     aria-invalid={!!errors.password}
                     {...register("password", {
                        required: "Password is required",
                        minLength: { value: 8, message: "Min 8 characters" },
                        validate: (value) =>
                           passwordRegex.test(value) ||
                           "Need one uppercase, one lowercase and one digit",
                     })}
                  />
                  {errors.password && (
                     <p className="form-error text-sm" aria-live="polite">
                        {errors.password.message}
                     </p>
                  )}
               </div>

               {/* Confirm Password */}
               <div className="form-group">
                  <Label className="form-label text-sm font-bold" htmlFor="confirmPassword">
                     Confirm Password
                  </Label>
                  <Input
                     id="confirmPassword"
                     className="form-input"
                     placeholder="*********"
                     type="password"
                     autoComplete="new-password"
                     aria-invalid={!!errors.confirmPassword}
                     {...register("confirmPassword", {
                        required: "Please confirm your password",
                        validate: (value) =>
                           value === getValues("password") ||
                           "Passwords do not match",
                     })}
                  />
                  {errors.confirmPassword && (
                     <p className="form-error text-sm" aria-live="polite">
                        {errors.confirmPassword.message}
                     </p>
                  )}
               </div>

               {/* NO TERMS YET */}
               {/* Terms */}
               {/* <div className="form-group form-legal">
            <div className="checkbox-container">
            <input
               id="acceptTerms"
               type="checkbox"
               className="checkbox-input"
               aria-invalid={!!errors.acceptTerms}
               {...register("acceptTerms", {
               validate: v => v === true || "You must accept the terms",
               })}
            />

            <label htmlFor="acceptTerms" className="checkbox-label text-sm">
               By clicking Register, you agree to our{" "}
               <a className="checkbox-link underline" href="/terms" target="_blank" rel="noopener noreferrer">Terms of Service</a>
               {" "}and{" "}
               <a className="checkbox-link underline" href="/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a>.
            </label>
            </div>

            {errors.acceptTerms && (
            <p className="form-error text-sm" aria-live="polite">{errors.acceptTerms.message}</p>
            )}
        </div> */}

               {/* Submit */}
               <Button
                  type="submit"
                  className="form-button"
                  disabled={isSubmitting}
               >
                  {isSubmitting ? "Registering..." : "Register"}
               </Button>

               {/* Sign in */}
               <p className="form-signin">
                  Already have an account? <a href="/signin">Sign in</a>
               </p>
            </form>
         </div>
      </div>
   );
};

export default RegistrationForm;